### ISSUE TITLE
PRACTICA 5

### ISSUE THREAD

**Issue by Kim-Mendoza3** [SistemasTecTlaxiaco/actividad-5-diseno-de-estructura-de-libreria-dll-danonino-programmers#1]
REPORTE DE PRACTICA 4:
https://drive.google.com/file/d/1lyrjWqNUnsQhwMasykHBQGqtjDPL-_UD/view?usp=sharing

**Comment by KevCH24** [comment]
Calificación: 20 
Cumplió con la rubricas establecidas.

**Comment by josealfredo79** [comment]
bien hecho y revisado...
